export const API_ENDPOINTS = {
  COVID_19: 'https://pomber.github.io/covid19/timeseries.json',
  EUROPEAN_COUNTRIES: 'https://restcountries.eu/rest/v2/region/europe',
};

export const EU_COUNTRIES = {
  Austria: { alpha2Code: 'at', alpha3Code: 'AUT', name: 'Austria' },
  Belgium: { alpha2Code: 'be', alpha3Code: 'BEL', name: 'Belgium' },
  Bulgaria: { alpha2Code: 'bg', alpha3Code: 'BGR', name: 'Bulgaria' },
  Croatia: { alpha2Code: 'hr', alpha3Code: 'HRV', name: 'Croatia' },
  Cyprus: { alpha2Code: 'cy', alpha3Code: 'CYP', name: 'Cyprus' },
  Czechia: { alpha2Code: 'cz', alpha3Code: 'CZE', name: 'Czechia' },
  Denmark: { alpha2Code: 'dk', alpha3Code: 'DNK', name: 'Denmark' },
  Estonia: { alpha2Code: 'ee', alpha3Code: 'EST', name: 'Estonia' },
  Finland: { alpha2Code: 'fi', alpha3Code: 'FIN', name: 'Finland' },
  France: { alpha2Code: 'fr', alpha3Code: 'FRA', name: 'France' },
  Germany: { alpha2Code: 'de', alpha3Code: 'DEU', name: 'Germany' },
  Greece: { alpha2Code: 'gr', alpha3Code: 'GRC', name: 'Greece' },
  Hungary: { alpha2Code: 'hu', alpha3Code: 'HUN', name: 'Hungary' },
  Ireland: { alpha2Code: 'ie', alpha3Code: 'IRL', name: 'Ireland' },
  Italy: { alpha2Code: 'it', alpha3Code: 'ITA', name: 'Italy' },
  Latvia: { alpha2Code: 'lv', alpha3Code: 'LVA', name: 'Latvia' },
  Lithuania: { alpha2Code: 'lt', alpha3Code: 'LTU', name: 'Lithuania' },
  Luxembourg: { alpha2Code: 'lu', alpha3Code: 'LUX', name: 'Luxembourg' },
  Malta: { alpha2Code: 'mt', alpha3Code: 'MLT', name: 'Malta' },
  Netherlands: { alpha2Code: 'nl', alpha3Code: 'NLD', name: 'Netherlands' },
  Poland: { alpha2Code: 'pl', alpha3Code: 'POL', name: 'Poland' },
  Portugal: { alpha2Code: 'pt', alpha3Code: 'PRT', name: 'Portugal' },
  Romania: { alpha2Code: 'ro', alpha3Code: 'ROU', name: 'Romania' },
  Slovakia: { alpha2Code: 'sk', alpha3Code: 'SVK', name: 'Slovakia' },
  Slovenia: { alpha2Code: 'si', alpha3Code: 'SVN', name: 'Slovenia' },
  Spain: { alpha2Code: 'es', alpha3Code: 'ESP', name: 'Spain' },
  Sweden: { alpha2Code: 'se', alpha3Code: 'SWE', name: 'Sweden' },
  'United Kingdom': {
    alpha2Code: 'gb',
    alpha3Code: 'GBR',
    formerEUcountry: true,
    name: 'United Kingdom',
  },
};

export const MONTHS = [
  ['January', 'Jan'],
  ['February', 'Feb'],
  ['March', 'Mar'],
  ['April', 'Apr'],
  ['May', 'May'],
  ['June', 'Jun'],
  ['July', 'Jul'],
  ['August', 'Aug'],
  ['September', 'Sep'],
  ['October', 'Oct'],
  ['November', 'Nov'],
  ['December', 'Dec'],
];
