export const DATA_URL = 'https://pomber.github.io/covid19/timeseries.json';

export const EU_COUNTRIES = [
  'Austria',
  'Belgium',
  'Bulgaria',
  'Croatia',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Hungary',
  'Ireland',
  'Italy',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Netherlands',
  'Poland',
  'Portugal',
  'Romania',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Sweden',
  'United Kingdom',
];

export const FORMER_EU_COUNTRIES = ['United Kingdom'];

export const EU_FLAGS = {
  Austria: { country_code: 'at' },
  Belgium: { country_code: 'be' },
  Bulgaria: { country_code: 'bg' },
  Croatia: { country_code: 'hr' },
  Cyprus: { country_code: 'cy' },
  Czechia: { country_code: 'cz' },
  Denmark: { country_code: 'dk' },
  Estonia: { country_code: 'ee' },
  Finland: { country_code: 'fi' },
  France: { country_code: 'fr' },
  Germany: { country_code: 'de' },
  Greece: { country_code: 'gr' },
  Hungary: { country_code: 'hu' },
  Ireland: { country_code: 'ie' },
  Italy: { country_code: 'it' },
  Latvia: { country_code: 'lv' },
  Lithuania: { country_code: 'lt' },
  Luxembourg: { country_code: 'lu' },
  Malta: { country_code: 'mt' },
  Netherlands: { country_code: 'nl' },
  Poland: { country_code: 'pl' },
  Portugal: { country_code: 'pt' },
  Romania: { country_code: 'ro' },
  Slovakia: { country_code: 'sk' },
  Slovenia: { country_code: 'si' },
  Spain: { country_code: 'es' },
  Sweden: { country_code: 'se' },
  'United Kingdom': { country_code: 'gb' },
};

export const MONTHS = [
  ['January', 'Jan'],
  ['February', 'Feb'],
  ['March', 'Mar'],
  ['April', 'Apr'],
  ['May', 'May'],
  ['June', 'Jun'],
  ['July', 'Jul'],
  ['August', 'Aug'],
  ['September', 'Sep'],
  ['October', 'Oct'],
  ['November', 'Nov'],
  ['December', 'Dec'],
];
