export const DATA_URL = 'https://pomber.github.io/covid19/timeseries.json';

export const EU_COUNTRIES = {
  Austria: { alpha2Code: 'at', alpha3Code: 'AUT' },
  Belgium: { alpha2Code: 'be', alpha3Code: 'BEL' },
  Bulgaria: { alpha2Code: 'bg', alpha3Code: 'BGR' },
  Croatia: { alpha2Code: 'hr', alpha3Code: 'HRV' },
  Cyprus: { alpha2Code: 'cy', alpha3Code: 'CYP' },
  Czechia: { alpha2Code: 'cz', alpha3Code: 'CZE' },
  Denmark: { alpha2Code: 'dk', alpha3Code: 'DNK' },
  Estonia: { alpha2Code: 'ee', alpha3Code: 'EST' },
  Finland: { alpha2Code: 'fi', alpha3Code: 'FIN' },
  France: { alpha2Code: 'fr', alpha3Code: 'FRA' },
  Germany: { alpha2Code: 'de', alpha3Code: 'DEU' },
  Greece: { alpha2Code: 'gr', alpha3Code: 'GRC' },
  Hungary: { alpha2Code: 'hu', alpha3Code: 'HUN' },
  Ireland: { alpha2Code: 'ie', alpha3Code: 'IRL' },
  Italy: { alpha2Code: 'it', alpha3Code: 'ITA' },
  Latvia: { alpha2Code: 'lv', alpha3Code: 'LVA' },
  Lithuania: { alpha2Code: 'lt', alpha3Code: 'LTU' },
  Luxembourg: { alpha2Code: 'lu', alpha3Code: 'LUX' },
  Malta: { alpha2Code: 'mt', alpha3Code: 'MLT' },
  Netherlands: { alpha2Code: 'nl', alpha3Code: 'NLD' },
  Poland: { alpha2Code: 'pl', alpha3Code: 'POL' },
  Portugal: { alpha2Code: 'pt', alpha3Code: 'PRT' },
  Romania: { alpha2Code: 'ro', alpha3Code: 'ROU' },
  Slovakia: { alpha2Code: 'sk', alpha3Code: 'SVK' },
  Slovenia: { alpha2Code: 'si', alpha3Code: 'SVN' },
  Spain: { alpha2Code: 'es', alpha3Code: 'ESP' },
  Sweden: { alpha2Code: 'se', alpha3Code: 'SWE' },
  'United Kingdom': {
    alpha2Code: 'gb',
    alpha3Code: 'GBR',
    formerEUcountry: true,
  },
};

export const MONTHS = [
  ['January', 'Jan'],
  ['February', 'Feb'],
  ['March', 'Mar'],
  ['April', 'Apr'],
  ['May', 'May'],
  ['June', 'Jun'],
  ['July', 'Jul'],
  ['August', 'Aug'],
  ['September', 'Sep'],
  ['October', 'Oct'],
  ['November', 'Nov'],
  ['December', 'Dec'],
];
